name: WebAssembly
on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/webassembly.yml'
  release:
    types: [published]
    
permissions:
  contents: write  # Required for pushing changes to the repo

jobs:
  build:
    runs-on: windows-latest
    
    env:
      PROJECT_NAME: ${{ github.event.repository.name }}
      PROJECT_BUILD_PATH: ${{ github.event.repository.name }}\\src
      PROJECT_RELEASE_PATH: ${{ github.event.repository.name }}_dev_wasm
      
    steps:
    - name: Checkout this repo
      uses: actions/checkout@main
      with:
        path: ${{ env.PROJECT_NAME }}

    - name: Checkout raylib repo
      uses: actions/checkout@v4
      with:
        repository: raysan5/raylib
        path: raylib
  
    - name: Setup emsdk
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 3.1.64
        actions-cache-folder: 'emsdk-cache'
        
    - name: Setup Release Paths
      run: |
        echo "PROJECT_RELEASE_PATH=${{ env.PROJECT_NAME }}_v${{ github.event.release.tag_name }}_wasm" >> $GITHUB_ENV
      shell: bash
      if: github.event_name == 'release' && github.event.action == 'published'
    
    - name: Setup Environment
      run: mkdir ${{ env.PROJECT_RELEASE_PATH }}
   
    - name: Build raylib Library
      run: |
        cd raylib/src
        emcc -v
        make PLATFORM=PLATFORM_WEB RAYLIB_BUILD_MODE=RELEASE RAYLIB_LIBTYPE=STATIC EMSDK_PATH="D:/a/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}/emsdk-cache/emsdk-main" RAYLIB_PROJECT_RELEASE_PATH=. -B

    - name: Build Product
      run: |
        cd ${{ env.PROJECT_NAME }}/src
        make PLATFORM=PLATFORM_WEB BUILD_MODE=RELEASE EMSDK_PATH="D:/a/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}/emsdk-cache/emsdk-main" PROJECT_BUILD_PATH=. RAYLIB_SRC_PATH=../../raylib/src -B
  
    - name: Move Build to Docs
      run: |
        mkdir -p ${{ env.PROJECT_NAME }}/docs
        cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }}.html ${{ env.PROJECT_NAME }}/docs/index.html
        cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }}.wasm ${{ env.PROJECT_NAME }}/docs/
        cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }}.js ${{ env.PROJECT_NAME }}/docs/
        cp ${{ env.PROJECT_BUILD_PATH }}/${{ env.PROJECT_NAME }}.data ${{ env.PROJECT_NAME }}/docs/
      shell: bash
      
    - name: Commit and Push Changes
      run: |
        cd ${{ env.PROJECT_NAME }}
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add docs/
        git commit -m "Deploy latest build to GitHub Pages"
        git push origin main
      shell: bash
