name: WebAssembly

on:
  workflow_dispatch:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/webassembly.yml'
  release:
    types: [published]

permissions:
  contents: write  # Required for committing to the repository

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v4
      with:
        path: ${{ github.event.repository.name }}

    # (Your existing steps for building WebAssembly)

    - name: Generate Artifacts
      # (Your existing artifact generation commands)

    - name: Upload Artifact to Release
      # (Your existing release upload commands)

    - name: Deploy to GitHub Pages
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        rm -rf docs/*  # Clear old docs
        mkdir -p docs
        cp -r ${{ env.PROJECT_RELEASE_PATH }}/* docs/
        git add docs/
        git commit -m "Deploy latest build to GitHub Pages"
        git push origin main
      shell: bash
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
